name: "Build Docker image"
description: "Automation tool for publishing Docker images"
author: "4ops"
branding:
  icon: "box"
  color: "blue"
inputs:
  registry:
    description: "Container registry"
    default: "docker.io"
  username:
    description: "Registry username"
    required: true
  password:
    description: "Registry password"
    required: true
  context:
    description: "Path to Docker context"
    default: "."
  dockerfile:
    description: "Path to Dockerfile"
    default: "Dockerfile"
  image:
    description: "Image name"
    required: true
  tag:
    description: "Image tag"
    required: true
  latest:
    description: "Second tag will be pushed if non-empty value"
    default: "latest"
  target:
    description: "Build target"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.registry }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.context }}
    - ${{ inputs.dockerfile }}
    - ${{ inputs.image }}
    - ${{ inputs.tag }}
    - ${{ inputs.latest }}
    - ${{ inputs.target }}
